# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Iniitalize
      shell: cmd
      run: initialize.bat

    - name: Build
      shell: cmd
      run: build.bat

  linux:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4.1.0

        - name: Iniitalize
          run: ./initialize.sh
  
        - name: Build
          run: ./build.sh